### ISSUE TITLE
Animated Blobs Loading Slowly on Firefox

### ISSUE THREAD

**Issue by rmehri01** [getreflect/reflect-chrome#76]
I'm using Firefox and get stuck on this page for like 1-2 minutes:

![image](https://user-images.githubusercontent.com/52933714/92545860-4dfb4c00-f20e-11ea-97f3-709857dfd0fa.png)

As well, after the animated blobs load in, they move pretty slow when hovered over:

![reflect](https://user-images.githubusercontent.com/52933714/92546202-40929180-f20f-11ea-8dc5-bf7ab2baf174.gif)

**Comment by jackyzha0** [comment]
After quick discussion with the team, we've decided to park this new graphics release for Firefox and keep it at the 1.2.0 release. Due to the small userbase (<35 users), we feel the extra energy required to maintain and backport the Chrome functionality to Firefox could be better spent.

Closing this issue as this fix is no longer required
